"""empty message

Revision ID: e24fcfd1e6a4
Revises: d8c9f3d2fd9d
Create Date: 2021-05-30 20:58:19.668104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24fcfd1e6a4'
down_revision = 'd8c9f3d2fd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('resolved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'resolved')
    # ### end Alembic commands ###
